vim.keymap.set("n", "<leader>to", function()
	require("trouble").open()
end)
vim.keymap.set("n", "<leader>to", function()
	require("trouble").open("workspace_diagnostics")
end)
vim.keymap.set("n", "<leader>td", function()
	require("trouble").open("document_diagnostics")
end)
vim.keymap.set("n", "<leader>tq", function()
	require("trouble").open("quickfix")
end)
vim.keymap.set("n", "<leader>tl", function()
	require("trouble").open("loclist")
end)
vim.keymap.set("n", "gR", function()
	require("trouble").open("lsp_references")
end)
